import { createClient } from "@hey-api/openapi-ts";
import { mkdir, mkdtemp, readdir, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterAll, beforeAll, describe, expect, test } from "vite-plus/test";

import { defineConfig } from "./config";
import { toCamelCase, toMswPath } from "./utils";

// ──────────────────────────────────────────────
// toCamelCase
// ──────────────────────────────────────────────

describe("toCamelCase", () => {
  test("先頭文字を小文字にする", () => {
    expect(toCamelCase("Hello")).toBe("hello");
  });

  test("すでに小文字始まりの場合は変化なし", () => {
    expect(toCamelCase("hello")).toBe("hello");
  });

  test("残りの文字はそのまま保持する", () => {
    expect(toCamelCase("AccountGetAccounts")).toBe("accountGetAccounts");
  });

  test("1文字の文字列に対応する", () => {
    expect(toCamelCase("A")).toBe("a");
  });
});

// ──────────────────────────────────────────────
// toMswPath
// ──────────────────────────────────────────────

describe("toMswPath", () => {
  test("パスパラメータを :param 形式に変換する", () => {
    expect(toMswPath("/users/{id}")).toBe("/users/:id");
  });

  test("複数のパスパラメータを変換する", () => {
    expect(toMswPath("/users/{userId}/posts/{postId}")).toBe("/users/:userId/posts/:postId");
  });

  test("パスパラメータがない場合はそのまま返す", () => {
    expect(toMswPath("/accounts")).toBe("/accounts");
  });

  test("ハイフンを含むパラメータ名の特殊文字を除去する", () => {
    expect(toMswPath("/items/{item-id}")).toBe("/items/:itemid");
  });

  test("ドットを含むパラメータ名の特殊文字を除去する", () => {
    expect(toMswPath("/v2/{api.version}/data")).toBe("/v2/:apiversion/data");
  });
});

// ──────────────────────────────────────────────
// 統合テスト: createClient でコード生成
// ──────────────────────────────────────────────

const minimalSpec = {
  openapi: "3.1.0",
  info: { title: "Test API", version: "1.0.0" },
  paths: {
    "/accounts": {
      get: {
        operationId: "accountGetAccounts",
        responses: {
          200: {
            description: "Success",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    accounts: {
                      type: "array",
                      items: { type: "object" },
                    },
                    total: { type: "number" },
                  },
                  required: ["accounts", "total"],
                },
              },
            },
          },
        },
      },
    },
    "/accounts/{id}": {
      delete: {
        operationId: "accountDeleteAccount",
        parameters: [
          {
            name: "id",
            in: "path",
            required: true,
            schema: { type: "string" },
          },
        ],
        responses: {
          204: { description: "Deleted" },
        },
      },
    },
  },
};

describe("MSW プラグイン 統合テスト", () => {
  let outputDir: string;
  let generated: string;

  beforeAll(async () => {
    outputDir = await mkdtemp(path.join(os.tmpdir(), "hey-api-msw-test-"));
    await mkdir(outputDir, { recursive: true });

    await createClient({
      input: { path: minimalSpec as any },
      output: outputDir,
      plugins: ["@hey-api/typescript", defineConfig({ bundleFunctionName: "getTestMock" })],
    });

    const files = await readdir(outputDir);
    const mswFile = files.find((f) => f.includes("my-msw-plugin"));
    if (!mswFile) throw new Error(`生成ファイルが見つかりません: ${files.join(", ")}`);
    generated = await readFile(path.join(outputDir, mswFile), "utf-8");
  });

  afterAll(async () => {
    await rm(outputDir, { recursive: true, force: true });
  });

  test("生成されたファイルのスナップショット", () => {
    expect(generated).toMatchInlineSnapshot(`
    	"// This file is auto-generated by @hey-api/openapi-ts

    	import { http, type HttpRequestResolverExtras, HttpResponse, type PathParams, type RequestHandlerOptions } from 'msw';

    	import type { AccountDeleteAccountResponses, AccountGetAccountsResponses } from './types.gen.js';

    	export const accountGetAccountsMockHandler = (overrideResponse?: AccountGetAccountsResponses | ((info: HttpRequestResolverExtras<PathParams>) => AccountGetAccountsResponses | Response | Promise<AccountGetAccountsResponses | Response>), options?: {
    	    status?: number;
    	} & RequestHandlerOptions) => {
    	    const status = options?.status ?? 200;
    	    return http.get('*/accounts', async (info) => {
    	        if (typeof overrideResponse === 'function') {
    	            const result = await overrideResponse(info);
    	            if (result instanceof Response) {
    	                return result;
    	            }
    	            return HttpResponse.json(result, { status });
    	        }
    	        if (overrideResponse !== undefined) {
    	            return HttpResponse.json(overrideResponse, { status });
    	        }
    	        return new Response(null, { status: 501, statusText: 'Not Implemented' });
    	    }, options);
    	};

    	export const accountDeleteAccountMockHandler = (overrideResponse?: AccountDeleteAccountResponses | ((info: HttpRequestResolverExtras<PathParams>) => AccountDeleteAccountResponses | Response | Promise<AccountDeleteAccountResponses | Response>), options?: {
    	    status?: number;
    	} & RequestHandlerOptions) => {
    	    const status = options?.status ?? 200;
    	    return http.delete('*/accounts/:id', async (info) => {
    	        if (typeof overrideResponse === 'function') {
    	            const result = await overrideResponse(info);
    	            if (result instanceof Response) {
    	                return result;
    	            }
    	            return HttpResponse.json(result, { status });
    	        }
    	        if (overrideResponse !== undefined) {
    	            return HttpResponse.json(overrideResponse, { status });
    	        }
    	        return new Response(null, { status: 501, statusText: 'Not Implemented' });
    	    }, options);
    	};

    	export const getTestMock = () => [accountGetAccountsMockHandler(), accountDeleteAccountMockHandler()];
    	"
    `);
  });
});
