// This file is auto-generated by @hey-api/openapi-ts

export const Account_AccountSchema = {
    type: 'object',
    required: ['id', 'name', 'modified', 'sort', 'active', 'local_id', 'website_id', 'parent_account_id'],
    properties: {
        id: {
            type: 'integer',
            format: 'int32',
            description: 'Unique account ID'
        },
        name: {
            type: 'string',
            description: 'Account name'
        },
        modified: {
            type: 'string',
            description: 'Last modified timestamp'
        },
        sort: {
            type: 'integer',
            format: 'int32',
            description: 'Sort order'
        },
        active: {
            type: 'integer',
            format: 'int32',
            description: 'Active status'
        },
        local_id: {
            type: 'integer',
            format: 'int32',
            description: 'Local account ID'
        },
        website_id: {
            type: 'integer',
            format: 'int32',
            description: 'Website ID'
        },
        parent_account_id: {
            type: 'integer',
            format: 'int32',
            description: 'Parent account ID'
        }
    }
} as const;

export const Category_CategorySchema = {
    type: 'object',
    required: ['id', 'name', 'mode', 'sort', 'parent_category_id', 'active', 'modified', 'local_id'],
    properties: {
        id: {
            type: 'integer',
            format: 'int32',
            description: 'Unique category ID'
        },
        name: {
            type: 'string',
            description: 'Category name'
        },
        mode: {
            type: 'string',
            enum: ['payment', 'income'],
            description: 'Type of category: "payment" or "income"'
        },
        sort: {
            type: 'integer',
            format: 'int32',
            description: 'Sort order'
        },
        parent_category_id: {
            type: 'integer',
            format: 'int32',
            description: 'Parent category ID'
        },
        active: {
            type: 'integer',
            format: 'int32',
            description: 'Active status'
        },
        modified: {
            type: 'string',
            description: 'Last modified timestamp'
        },
        local_id: {
            type: 'integer',
            format: 'int32',
            description: '(Undocumented)'
        }
    }
} as const;

export const ErrorResponseSchema = {
    type: 'object',
    required: ['error', 'message'],
    properties: {
        error: {
            type: 'boolean',
            enum: [true]
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const Genre_GenreSchema = {
    type: 'object',
    required: ['id', 'name', 'sort', 'active', 'category_id', 'parent_genre_id', 'modified', 'local_id'],
    properties: {
        id: {
            type: 'integer',
            format: 'int32',
            description: 'Unique genre ID'
        },
        name: {
            type: 'string',
            description: 'Genre name'
        },
        sort: {
            type: 'integer',
            format: 'int32',
            description: 'Sort order'
        },
        active: {
            type: 'integer',
            format: 'int32',
            description: 'Active status'
        },
        category_id: {
            type: 'integer',
            format: 'int32',
            description: 'Category ID this genre belongs to'
        },
        parent_genre_id: {
            type: 'integer',
            format: 'int32',
            description: 'Parent genre ID'
        },
        modified: {
            type: 'string',
            description: 'Last modified timestamp'
        },
        local_id: {
            type: 'integer',
            format: 'int32',
            description: '(Undocumented)'
        }
    }
} as const;

export const Money_MoneySchema = {
    type: 'object',
    required: ['id', 'mode', 'user_id', 'date', 'category_id', 'genre_id', 'to_account_id', 'from_account_id', 'amount', 'comment', 'active', 'name', 'receipt_id', 'place', 'created', 'currency_code'],
    properties: {
        id: {
            type: 'integer',
            format: 'int32',
            description: 'Unique input id'
        },
        mode: {
            type: 'string',
            enum: ['income', 'payment', 'transfer'],
            description: 'Type of transaction: income, payment, or transfer'
        },
        user_id: {
            type: 'integer',
            format: 'int32',
            description: 'User ID'
        },
        date: {
            type: 'string',
            description: 'Date of the transaction in YYYY-MM-DD format'
        },
        category_id: {
            type: 'integer',
            format: 'int32',
            description: 'Category ID'
        },
        genre_id: {
            type: 'integer',
            format: 'int32',
            description: 'Genre ID'
        },
        to_account_id: {
            type: 'integer',
            format: 'int32',
            description: 'Account ID for incoming transfer (for income or transfer)'
        },
        from_account_id: {
            type: 'integer',
            format: 'int32',
            description: 'Account ID for outgoing transfer (for payment or transfer)'
        },
        amount: {
            type: 'integer',
            format: 'int32',
            description: 'Amount without decimal point'
        },
        comment: {
            type: 'string',
            description: 'Comment or memo'
        },
        active: {
            type: 'integer',
            format: 'int32',
            description: 'Active status'
        },
        name: {
            type: 'string',
            description: 'Name of the item or product'
        },
        receipt_id: {
            type: 'integer',
            format: 'int32',
            description: 'Receipt ID'
        },
        place: {
            type: 'string',
            description: 'Place name'
        },
        created: {
            type: 'string',
            description: 'Creation timestamp'
        },
        currency_code: {
            type: 'string',
            description: 'Currency code'
        }
    }
} as const;

export const Money_MoneyResponseSchema = {
    type: 'object',
    required: ['money', 'user'],
    properties: {
        money: {
            type: 'object',
            properties: {
                id: {
                    type: 'integer',
                    format: 'int32',
                    description: 'Unique ID given by Zaim for each input'
                },
                modified: {
                    type: 'string',
                    description: 'Modification timestamp'
                },
                place_uid: {
                    type: 'string',
                    description: 'Place UID (only present if a place was specified)'
                }
            },
            required: ['id', 'modified']
        },
        place: {
            type: 'object',
            properties: {
                id: {
                    type: 'integer',
                    format: 'int32'
                },
                user_id: {
                    type: 'integer',
                    format: 'int32'
                },
                genre_id: {
                    type: 'integer',
                    format: 'int32'
                },
                category_id: {
                    type: 'integer',
                    format: 'int32'
                },
                account_id: {
                    type: 'integer',
                    format: 'int32'
                },
                transfer_account_id: {
                    type: 'integer',
                    format: 'int32'
                },
                mode: {
                    type: 'string'
                },
                place_uid: {
                    type: 'string'
                },
                service: {
                    type: 'string'
                },
                name: {
                    type: 'string'
                },
                original_name: {
                    type: 'string'
                },
                tel: {
                    type: 'string'
                },
                count: {
                    type: 'integer',
                    format: 'int32'
                },
                place_pattern_id: {
                    type: 'integer',
                    format: 'int32'
                },
                calc_flag: {
                    type: 'integer',
                    format: 'int32'
                },
                edit_flag: {
                    type: 'integer',
                    format: 'int32'
                },
                active: {
                    type: 'integer',
                    format: 'int32'
                },
                modified: {
                    type: 'string'
                },
                created: {
                    type: 'string'
                }
            },
            required: ['id', 'user_id', 'genre_id', 'category_id', 'account_id', 'transfer_account_id', 'mode', 'place_uid', 'service', 'name', 'original_name', 'tel', 'count', 'place_pattern_id', 'calc_flag', 'edit_flag', 'active', 'modified', 'created'],
            description: 'Place information (only present if a place was specified)'
        },
        user: {
            type: 'object',
            properties: {
                repeat_count: {
                    type: 'integer',
                    format: 'int32',
                    description: 'Number of consecutive days of recording'
                },
                day_count: {
                    type: 'integer',
                    format: 'int32',
                    description: 'Total number of days with records'
                },
                input_count: {
                    type: 'integer',
                    format: 'int32',
                    description: 'Total number of inputs by the user'
                }
            },
            required: ['repeat_count', 'day_count', 'input_count']
        }
    }
} as const;

export const Other_CurrencySchema = {
    type: 'object',
    required: ['currency_code', 'unit', 'name', 'point'],
    properties: {
        currency_code: {
            type: 'string',
            description: 'Currency code'
        },
        unit: {
            type: 'string',
            description: 'Currency unit symbol'
        },
        name: {
            type: 'string',
            description: 'Currency name'
        },
        point: {
            type: 'integer',
            format: 'int32',
            description: 'Number of decimal points'
        }
    }
} as const;

export const Other_DefaultAccountSchema = {
    type: 'object',
    required: ['id', 'name'],
    properties: {
        id: {
            type: 'integer',
            format: 'int32',
            description: 'Unique account ID'
        },
        name: {
            type: 'string',
            description: 'Account name'
        }
    }
} as const;

export const Other_DefaultCategorySchema = {
    type: 'object',
    required: ['id', 'mode', 'name'],
    properties: {
        id: {
            type: 'integer',
            format: 'int32',
            description: 'Unique category ID'
        },
        mode: {
            type: 'string',
            enum: ['payment', 'income'],
            description: 'Type of category: "payment" or "income"'
        },
        name: {
            type: 'string',
            description: 'Category name'
        }
    }
} as const;

export const Other_DefaultGenreSchema = {
    type: 'object',
    required: ['id', 'category_id', 'name'],
    properties: {
        id: {
            type: 'integer',
            format: 'int32',
            description: 'Unique genre ID'
        },
        category_id: {
            type: 'integer',
            format: 'int32',
            description: 'Category ID this genre belongs to'
        },
        name: {
            type: 'string',
            description: 'Genre name'
        }
    }
} as const;

export const User_UserSchema = {
    type: 'object',
    required: ['id', 'login', 'name', 'input_count', 'day_count', 'repeat_count', 'day', 'week', 'month', 'currency_code', 'profile_image_url', 'cover_image_url', 'profile_modified', 'created'],
    properties: {
        id: {
            type: 'integer',
            format: 'int32',
            description: 'Unique user ID'
        },
        login: {
            type: 'string',
            description: 'Unique string for user login'
        },
        name: {
            type: 'string',
            description: 'User name'
        },
        input_count: {
            type: 'integer',
            format: 'int32',
            description: 'Total number of inputs'
        },
        day_count: {
            type: 'integer',
            format: 'int32',
            description: 'Total number of days'
        },
        repeat_count: {
            type: 'integer',
            format: 'int32',
            description: 'Days of continuous recording'
        },
        day: {
            type: 'integer',
            format: 'int32',
            description: 'Start date of the month'
        },
        week: {
            type: 'integer',
            format: 'int32',
            description: 'First day of the week'
        },
        month: {
            type: 'integer',
            format: 'int32',
            description: 'Start date of the year'
        },
        currency_code: {
            type: 'string',
            description: 'Default currency code'
        },
        profile_image_url: {
            type: 'string',
            format: 'uri',
            description: "URL of the user's profile image"
        },
        cover_image_url: {
            type: 'string',
            format: 'uri',
            description: "URL of the user's cover image"
        },
        profile_modified: {
            type: 'string',
            description: "Last modified time of the user's profile"
        },
        created: {
            type: 'string',
            description: '(Undocumented) Createed time of user'
        }
    }
} as const;