// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { OtherGetDefaultAccountsData, OtherGetDefaultAccountsResponse, OtherGetDefaultAccountsError, OtherGetDefaultCategoriesData, OtherGetDefaultCategoriesResponse, OtherGetDefaultCategoriesError, OtherGetCurrenciesData, OtherGetCurrenciesResponse, OtherGetCurrenciesError, OtherGetDefaultGenresData, OtherGetDefaultGenresResponse, OtherGetDefaultGenresError, AccountGetAccountsData, AccountGetAccountsResponse, AccountGetAccountsError, CategoryGetCategoriesData, CategoryGetCategoriesResponse, CategoryGetCategoriesError, GenreGetGenresData, GenreGetGenresResponse, GenreGetGenresError, MoneyGetMoneyData, MoneyGetMoneyResponse, MoneyGetMoneyError, IncomeOperationsCreateData, IncomeOperationsCreateResponse, IncomeOperationsCreateError, IncomeOperationsDeleteData, IncomeOperationsDeleteResponse, IncomeOperationsDeleteError, IncomeOperationsUpdateData, IncomeOperationsUpdateResponse, IncomeOperationsUpdateError, PaymentOperationsCreateData, PaymentOperationsCreateResponse, PaymentOperationsCreateError, PaymentOperationsDeleteData, PaymentOperationsDeleteResponse, PaymentOperationsDeleteError, PaymentOperationsUpdateData, PaymentOperationsUpdateResponse, PaymentOperationsUpdateError, TransferOperationsCreateData, TransferOperationsCreateResponse, TransferOperationsCreateError, TransferOperationsDeleteData, TransferOperationsDeleteResponse, TransferOperationsDeleteError, TransferOperationsUpdateData, TransferOperationsUpdateResponse, TransferOperationsUpdateError, UserVerifyUserData, UserVerifyUserResponse, UserVerifyUserError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const otherGetDefaultAccounts = <ThrowOnError extends boolean = false>(options?: Options<OtherGetDefaultAccountsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<OtherGetDefaultAccountsResponse, OtherGetDefaultAccountsError, ThrowOnError>({
        url: '/v2/account',
        ...options
    });
};

export const otherGetDefaultCategories = <ThrowOnError extends boolean = false>(options?: Options<OtherGetDefaultCategoriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<OtherGetDefaultCategoriesResponse, OtherGetDefaultCategoriesError, ThrowOnError>({
        url: '/v2/category',
        ...options
    });
};

export const otherGetCurrencies = <ThrowOnError extends boolean = false>(options?: Options<OtherGetCurrenciesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<OtherGetCurrenciesResponse, OtherGetCurrenciesError, ThrowOnError>({
        url: '/v2/currency',
        ...options
    });
};

export const otherGetDefaultGenres = <ThrowOnError extends boolean = false>(options?: Options<OtherGetDefaultGenresData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<OtherGetDefaultGenresResponse, OtherGetDefaultGenresError, ThrowOnError>({
        url: '/v2/genre',
        ...options
    });
};

export const accountGetAccounts = <ThrowOnError extends boolean = false>(options: Options<AccountGetAccountsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<AccountGetAccountsResponse, AccountGetAccountsError, ThrowOnError>({
        url: '/v2/home/account',
        ...options
    });
};

export const categoryGetCategories = <ThrowOnError extends boolean = false>(options: Options<CategoryGetCategoriesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<CategoryGetCategoriesResponse, CategoryGetCategoriesError, ThrowOnError>({
        url: '/v2/home/category',
        ...options
    });
};

export const genreGetGenres = <ThrowOnError extends boolean = false>(options: Options<GenreGetGenresData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GenreGetGenresResponse, GenreGetGenresError, ThrowOnError>({
        url: '/v2/home/genre',
        ...options
    });
};

export const moneyGetMoney = <ThrowOnError extends boolean = false>(options: Options<MoneyGetMoneyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<MoneyGetMoneyResponse, MoneyGetMoneyError, ThrowOnError>({
        url: '/v2/home/money',
        ...options
    });
};

export const incomeOperationsCreate = <ThrowOnError extends boolean = false>(options: Options<IncomeOperationsCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<IncomeOperationsCreateResponse, IncomeOperationsCreateError, ThrowOnError>({
        url: '/v2/home/money/income',
        ...options
    });
};

export const incomeOperationsDelete = <ThrowOnError extends boolean = false>(options: Options<IncomeOperationsDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<IncomeOperationsDeleteResponse, IncomeOperationsDeleteError, ThrowOnError>({
        url: '/v2/home/money/income/{id}',
        ...options
    });
};

export const incomeOperationsUpdate = <ThrowOnError extends boolean = false>(options: Options<IncomeOperationsUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<IncomeOperationsUpdateResponse, IncomeOperationsUpdateError, ThrowOnError>({
        url: '/v2/home/money/income/{id}',
        ...options
    });
};

export const paymentOperationsCreate = <ThrowOnError extends boolean = false>(options: Options<PaymentOperationsCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PaymentOperationsCreateResponse, PaymentOperationsCreateError, ThrowOnError>({
        url: '/v2/home/money/payment',
        ...options
    });
};

export const paymentOperationsDelete = <ThrowOnError extends boolean = false>(options: Options<PaymentOperationsDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<PaymentOperationsDeleteResponse, PaymentOperationsDeleteError, ThrowOnError>({
        url: '/v2/home/money/payment/{id}',
        ...options
    });
};

export const paymentOperationsUpdate = <ThrowOnError extends boolean = false>(options: Options<PaymentOperationsUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PaymentOperationsUpdateResponse, PaymentOperationsUpdateError, ThrowOnError>({
        url: '/v2/home/money/payment/{id}',
        ...options
    });
};

export const transferOperationsCreate = <ThrowOnError extends boolean = false>(options: Options<TransferOperationsCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<TransferOperationsCreateResponse, TransferOperationsCreateError, ThrowOnError>({
        url: '/v2/home/money/transfer',
        ...options
    });
};

export const transferOperationsDelete = <ThrowOnError extends boolean = false>(options: Options<TransferOperationsDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<TransferOperationsDeleteResponse, TransferOperationsDeleteError, ThrowOnError>({
        url: '/v2/home/money/transfer/{id}',
        ...options
    });
};

export const transferOperationsUpdate = <ThrowOnError extends boolean = false>(options: Options<TransferOperationsUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<TransferOperationsUpdateResponse, TransferOperationsUpdateError, ThrowOnError>({
        url: '/v2/home/money/transfer/{id}',
        ...options
    });
};

export const userVerifyUser = <ThrowOnError extends boolean = false>(options?: Options<UserVerifyUserData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UserVerifyUserResponse, UserVerifyUserError, ThrowOnError>({
        url: '/v2/home/user/verify',
        ...options
    });
};