// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as ClientOptions, TDataShape } from "./client";
import { client as _heyApiClient } from "./client.gen";
import type {
	AccountGetAccountsData,
	AccountGetAccountsErrors,
	AccountGetAccountsResponses,
	CategoryGetCategoriesData,
	CategoryGetCategoriesErrors,
	CategoryGetCategoriesResponses,
	GenreGetGenresData,
	GenreGetGenresErrors,
	GenreGetGenresResponses,
	IncomeOperationsCreateData,
	IncomeOperationsCreateErrors,
	IncomeOperationsCreateResponses,
	IncomeOperationsDeleteData,
	IncomeOperationsDeleteErrors,
	IncomeOperationsDeleteResponses,
	IncomeOperationsUpdateData,
	IncomeOperationsUpdateErrors,
	IncomeOperationsUpdateResponses,
	MoneyGetMoneyData,
	MoneyGetMoneyErrors,
	MoneyGetMoneyResponses,
	OtherGetCurrenciesData,
	OtherGetCurrenciesErrors,
	OtherGetCurrenciesResponses,
	OtherGetDefaultAccountsData,
	OtherGetDefaultAccountsErrors,
	OtherGetDefaultAccountsResponses,
	OtherGetDefaultCategoriesData,
	OtherGetDefaultCategoriesErrors,
	OtherGetDefaultCategoriesResponses,
	OtherGetDefaultGenresData,
	OtherGetDefaultGenresErrors,
	OtherGetDefaultGenresResponses,
	PaymentOperationsCreateData,
	PaymentOperationsCreateErrors,
	PaymentOperationsCreateResponses,
	PaymentOperationsDeleteData,
	PaymentOperationsDeleteErrors,
	PaymentOperationsDeleteResponses,
	PaymentOperationsUpdateData,
	PaymentOperationsUpdateErrors,
	PaymentOperationsUpdateResponses,
	TransferOperationsCreateData,
	TransferOperationsCreateErrors,
	TransferOperationsCreateResponses,
	TransferOperationsDeleteData,
	TransferOperationsDeleteErrors,
	TransferOperationsDeleteResponses,
	TransferOperationsUpdateData,
	TransferOperationsUpdateErrors,
	TransferOperationsUpdateResponses,
	UserVerifyUserData,
	UserVerifyUserErrors,
	UserVerifyUserResponses,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

export const otherGetDefaultAccounts = <ThrowOnError extends boolean = false>(
	options?: Options<OtherGetDefaultAccountsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		OtherGetDefaultAccountsResponses,
		OtherGetDefaultAccountsErrors,
		ThrowOnError
	>({
		url: "/v2/account",
		...options,
	});
};

export const otherGetDefaultCategories = <ThrowOnError extends boolean = false>(
	options?: Options<OtherGetDefaultCategoriesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		OtherGetDefaultCategoriesResponses,
		OtherGetDefaultCategoriesErrors,
		ThrowOnError
	>({
		url: "/v2/category",
		...options,
	});
};

export const otherGetCurrencies = <ThrowOnError extends boolean = false>(
	options?: Options<OtherGetCurrenciesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		OtherGetCurrenciesResponses,
		OtherGetCurrenciesErrors,
		ThrowOnError
	>({
		url: "/v2/currency",
		...options,
	});
};

export const otherGetDefaultGenres = <ThrowOnError extends boolean = false>(
	options?: Options<OtherGetDefaultGenresData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		OtherGetDefaultGenresResponses,
		OtherGetDefaultGenresErrors,
		ThrowOnError
	>({
		url: "/v2/genre",
		...options,
	});
};

export const accountGetAccounts = <ThrowOnError extends boolean = false>(
	options: Options<AccountGetAccountsData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		AccountGetAccountsResponses,
		AccountGetAccountsErrors,
		ThrowOnError
	>({
		url: "/v2/home/account",
		...options,
	});
};

export const categoryGetCategories = <ThrowOnError extends boolean = false>(
	options: Options<CategoryGetCategoriesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		CategoryGetCategoriesResponses,
		CategoryGetCategoriesErrors,
		ThrowOnError
	>({
		url: "/v2/home/category",
		...options,
	});
};

export const genreGetGenres = <ThrowOnError extends boolean = false>(
	options: Options<GenreGetGenresData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GenreGetGenresResponses,
		GenreGetGenresErrors,
		ThrowOnError
	>({
		url: "/v2/home/genre",
		...options,
	});
};

export const moneyGetMoney = <ThrowOnError extends boolean = false>(
	options: Options<MoneyGetMoneyData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		MoneyGetMoneyResponses,
		MoneyGetMoneyErrors,
		ThrowOnError
	>({
		url: "/v2/home/money",
		...options,
	});
};

export const incomeOperationsCreate = <ThrowOnError extends boolean = false>(
	options: Options<IncomeOperationsCreateData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		IncomeOperationsCreateResponses,
		IncomeOperationsCreateErrors,
		ThrowOnError
	>({
		url: "/v2/home/money/income",
		...options,
	});
};

export const incomeOperationsDelete = <ThrowOnError extends boolean = false>(
	options: Options<IncomeOperationsDeleteData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		IncomeOperationsDeleteResponses,
		IncomeOperationsDeleteErrors,
		ThrowOnError
	>({
		url: "/v2/home/money/income/{id}",
		...options,
	});
};

export const incomeOperationsUpdate = <ThrowOnError extends boolean = false>(
	options: Options<IncomeOperationsUpdateData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).put<
		IncomeOperationsUpdateResponses,
		IncomeOperationsUpdateErrors,
		ThrowOnError
	>({
		url: "/v2/home/money/income/{id}",
		...options,
	});
};

export const paymentOperationsCreate = <ThrowOnError extends boolean = false>(
	options: Options<PaymentOperationsCreateData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PaymentOperationsCreateResponses,
		PaymentOperationsCreateErrors,
		ThrowOnError
	>({
		url: "/v2/home/money/payment",
		...options,
	});
};

export const paymentOperationsDelete = <ThrowOnError extends boolean = false>(
	options: Options<PaymentOperationsDeleteData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		PaymentOperationsDeleteResponses,
		PaymentOperationsDeleteErrors,
		ThrowOnError
	>({
		url: "/v2/home/money/payment/{id}",
		...options,
	});
};

export const paymentOperationsUpdate = <ThrowOnError extends boolean = false>(
	options: Options<PaymentOperationsUpdateData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).put<
		PaymentOperationsUpdateResponses,
		PaymentOperationsUpdateErrors,
		ThrowOnError
	>({
		url: "/v2/home/money/payment/{id}",
		...options,
	});
};

export const transferOperationsCreate = <ThrowOnError extends boolean = false>(
	options: Options<TransferOperationsCreateData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		TransferOperationsCreateResponses,
		TransferOperationsCreateErrors,
		ThrowOnError
	>({
		url: "/v2/home/money/transfer",
		...options,
	});
};

export const transferOperationsDelete = <ThrowOnError extends boolean = false>(
	options: Options<TransferOperationsDeleteData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		TransferOperationsDeleteResponses,
		TransferOperationsDeleteErrors,
		ThrowOnError
	>({
		url: "/v2/home/money/transfer/{id}",
		...options,
	});
};

export const transferOperationsUpdate = <ThrowOnError extends boolean = false>(
	options: Options<TransferOperationsUpdateData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).put<
		TransferOperationsUpdateResponses,
		TransferOperationsUpdateErrors,
		ThrowOnError
	>({
		url: "/v2/home/money/transfer/{id}",
		...options,
	});
};

export const userVerifyUser = <ThrowOnError extends boolean = false>(
	options?: Options<UserVerifyUserData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		UserVerifyUserResponses,
		UserVerifyUserErrors,
		ThrowOnError
	>({
		url: "/v2/home/user/verify",
		...options,
	});
};
