// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { OtherGetDefaultAccountsError, OtherGetDefaultAccountsResponse, OtherGetDefaultCategoriesError, OtherGetDefaultCategoriesResponse, OtherGetCurrenciesError, OtherGetCurrenciesResponse, OtherGetDefaultGenresError, OtherGetDefaultGenresResponse, AccountGetAccountsData, AccountGetAccountsError, AccountGetAccountsResponse, CategoryGetCategoriesData, CategoryGetCategoriesError, CategoryGetCategoriesResponse, GenreGetGenresData, GenreGetGenresError, GenreGetGenresResponse, MoneyGetMoneyData, MoneyGetMoneyError, MoneyGetMoneyResponse, IncomeOperationsCreateData, IncomeOperationsCreateError, IncomeOperationsCreateResponse, IncomeOperationsUpdateData, IncomeOperationsUpdateError, IncomeOperationsUpdateResponse, IncomeOperationsDeleteData, IncomeOperationsDeleteError, IncomeOperationsDeleteResponse, PaymentOperationsCreateData, PaymentOperationsCreateError, PaymentOperationsCreateResponse, PaymentOperationsUpdateData, PaymentOperationsUpdateError, PaymentOperationsUpdateResponse, PaymentOperationsDeleteData, PaymentOperationsDeleteError, PaymentOperationsDeleteResponse, TransferOperationsCreateData, TransferOperationsCreateError, TransferOperationsCreateResponse, TransferOperationsUpdateData, TransferOperationsUpdateError, TransferOperationsUpdateResponse, TransferOperationsDeleteData, TransferOperationsDeleteError, TransferOperationsDeleteResponse, UserVerifyUserError, UserVerifyUserResponse } from './types.gen';

export const client = createClient(createConfig());

export const otherGetDefaultAccounts = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<OtherGetDefaultAccountsResponse, OtherGetDefaultAccountsError, ThrowOnError>({
    ...options,
    url: '/v2/account'
}); };

export const otherGetDefaultCategories = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<OtherGetDefaultCategoriesResponse, OtherGetDefaultCategoriesError, ThrowOnError>({
    ...options,
    url: '/v2/category'
}); };

export const otherGetCurrencies = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<OtherGetCurrenciesResponse, OtherGetCurrenciesError, ThrowOnError>({
    ...options,
    url: '/v2/currency'
}); };

export const otherGetDefaultGenres = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<OtherGetDefaultGenresResponse, OtherGetDefaultGenresError, ThrowOnError>({
    ...options,
    url: '/v2/genre'
}); };

export const accountGetAccounts = <ThrowOnError extends boolean = false>(options: Options<AccountGetAccountsData, ThrowOnError>) => { return (options?.client ?? client).get<AccountGetAccountsResponse, AccountGetAccountsError, ThrowOnError>({
    ...options,
    url: '/v2/home/account'
}); };

export const categoryGetCategories = <ThrowOnError extends boolean = false>(options: Options<CategoryGetCategoriesData, ThrowOnError>) => { return (options?.client ?? client).get<CategoryGetCategoriesResponse, CategoryGetCategoriesError, ThrowOnError>({
    ...options,
    url: '/v2/home/category'
}); };

export const genreGetGenres = <ThrowOnError extends boolean = false>(options: Options<GenreGetGenresData, ThrowOnError>) => { return (options?.client ?? client).get<GenreGetGenresResponse, GenreGetGenresError, ThrowOnError>({
    ...options,
    url: '/v2/home/genre'
}); };

export const moneyGetMoney = <ThrowOnError extends boolean = false>(options: Options<MoneyGetMoneyData, ThrowOnError>) => { return (options?.client ?? client).get<MoneyGetMoneyResponse, MoneyGetMoneyError, ThrowOnError>({
    ...options,
    url: '/v2/home/money'
}); };

export const incomeOperationsCreate = <ThrowOnError extends boolean = false>(options: Options<IncomeOperationsCreateData, ThrowOnError>) => { return (options?.client ?? client).post<IncomeOperationsCreateResponse, IncomeOperationsCreateError, ThrowOnError>({
    ...options,
    url: '/v2/home/money/income'
}); };

export const incomeOperationsUpdate = <ThrowOnError extends boolean = false>(options: Options<IncomeOperationsUpdateData, ThrowOnError>) => { return (options?.client ?? client).put<IncomeOperationsUpdateResponse, IncomeOperationsUpdateError, ThrowOnError>({
    ...options,
    url: '/v2/home/money/income/{id}'
}); };

export const incomeOperationsDelete = <ThrowOnError extends boolean = false>(options: Options<IncomeOperationsDeleteData, ThrowOnError>) => { return (options?.client ?? client).delete<IncomeOperationsDeleteResponse, IncomeOperationsDeleteError, ThrowOnError>({
    ...options,
    url: '/v2/home/money/income/{id}'
}); };

export const paymentOperationsCreate = <ThrowOnError extends boolean = false>(options: Options<PaymentOperationsCreateData, ThrowOnError>) => { return (options?.client ?? client).post<PaymentOperationsCreateResponse, PaymentOperationsCreateError, ThrowOnError>({
    ...options,
    url: '/v2/home/money/payment'
}); };

export const paymentOperationsUpdate = <ThrowOnError extends boolean = false>(options: Options<PaymentOperationsUpdateData, ThrowOnError>) => { return (options?.client ?? client).put<PaymentOperationsUpdateResponse, PaymentOperationsUpdateError, ThrowOnError>({
    ...options,
    url: '/v2/home/money/payment/{id}'
}); };

export const paymentOperationsDelete = <ThrowOnError extends boolean = false>(options: Options<PaymentOperationsDeleteData, ThrowOnError>) => { return (options?.client ?? client).delete<PaymentOperationsDeleteResponse, PaymentOperationsDeleteError, ThrowOnError>({
    ...options,
    url: '/v2/home/money/payment/{id}'
}); };

export const transferOperationsCreate = <ThrowOnError extends boolean = false>(options: Options<TransferOperationsCreateData, ThrowOnError>) => { return (options?.client ?? client).post<TransferOperationsCreateResponse, TransferOperationsCreateError, ThrowOnError>({
    ...options,
    url: '/v2/home/money/transfer'
}); };

export const transferOperationsUpdate = <ThrowOnError extends boolean = false>(options: Options<TransferOperationsUpdateData, ThrowOnError>) => { return (options?.client ?? client).put<TransferOperationsUpdateResponse, TransferOperationsUpdateError, ThrowOnError>({
    ...options,
    url: '/v2/home/money/transfer/{id}'
}); };

export const transferOperationsDelete = <ThrowOnError extends boolean = false>(options: Options<TransferOperationsDeleteData, ThrowOnError>) => { return (options?.client ?? client).delete<TransferOperationsDeleteResponse, TransferOperationsDeleteError, ThrowOnError>({
    ...options,
    url: '/v2/home/money/transfer/{id}'
}); };

export const userVerifyUser = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<UserVerifyUserResponse, UserVerifyUserError, ThrowOnError>({
    ...options,
    url: '/v2/home/user/verify'
}); };