// This file is auto-generated by @hey-api/openapi-ts

export type Account_Account = {
    /**
     * Unique account ID
     */
    id: number;
    /**
     * Account name
     */
    name: string;
    /**
     * Last modified timestamp
     */
    modified: string;
    /**
     * Sort order
     */
    sort: number;
    /**
     * Active status
     */
    active: number;
    /**
     * Local account ID
     */
    local_id: number;
    /**
     * Website ID
     */
    website_id: number;
    /**
     * Parent account ID
     */
    parent_account_id: number;
};

export type Category_Category = {
    /**
     * Unique category ID
     */
    id: number;
    /**
     * Category name
     */
    name: string;
    /**
     * Type of category: "payment" or "income"
     */
    mode: 'payment' | 'income';
    /**
     * Sort order
     */
    sort: number;
    /**
     * Parent category ID
     */
    parent_category_id: number;
    /**
     * Active status
     */
    active: number;
    /**
     * Last modified timestamp
     */
    modified: string;
    /**
     * (Undocumented)
     */
    local_id: number;
};

/**
 * Type of category: "payment" or "income"
 */
export type mode = 'payment' | 'income';

export type ErrorResponse = {
    error: boolean;
    message: string;
};

export type Genre_Genre = {
    /**
     * Unique genre ID
     */
    id: number;
    /**
     * Genre name
     */
    name: string;
    /**
     * Sort order
     */
    sort: number;
    /**
     * Active status
     */
    active: number;
    /**
     * Category ID this genre belongs to
     */
    category_id: number;
    /**
     * Parent genre ID
     */
    parent_genre_id: number;
    /**
     * Last modified timestamp
     */
    modified: string;
    /**
     * (Undocumented)
     */
    local_id: number;
};

export type Money_Money = {
    /**
     * Unique input id
     */
    id: number;
    /**
     * Type of transaction: income, payment, or transfer
     */
    mode: 'income' | 'payment' | 'transfer';
    /**
     * User ID
     */
    user_id: number;
    /**
     * Date of the transaction in YYYY-MM-DD format
     */
    date: string;
    /**
     * Category ID
     */
    category_id: number;
    /**
     * Genre ID
     */
    genre_id: number;
    /**
     * Account ID for incoming transfer (for income or transfer)
     */
    to_account_id: number;
    /**
     * Account ID for outgoing transfer (for payment or transfer)
     */
    from_account_id: number;
    /**
     * Amount without decimal point
     */
    amount: number;
    /**
     * Comment or memo
     */
    comment: string;
    /**
     * Active status
     */
    active: number;
    /**
     * Name of the item or product
     */
    name: string;
    /**
     * Receipt ID
     */
    receipt_id: number;
    /**
     * Place name
     */
    place: string;
    /**
     * Creation timestamp
     */
    created: string;
    /**
     * Currency code
     */
    currency_code: string;
};

/**
 * Type of transaction: income, payment, or transfer
 */
export type mode2 = 'income' | 'payment' | 'transfer';

export type Money_MoneyResponse = {
    money: {
        /**
         * Unique ID given by Zaim for each input
         */
        id: number;
        /**
         * Modification timestamp
         */
        modified: string;
        /**
         * Place UID (only present if a place was specified)
         */
        place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
        id: number;
        user_id: number;
        genre_id: number;
        category_id: number;
        account_id: number;
        transfer_account_id: number;
        mode: string;
        place_uid: string;
        service: string;
        name: string;
        original_name: string;
        tel: string;
        count: number;
        place_pattern_id: number;
        calc_flag: number;
        edit_flag: number;
        active: number;
        modified: string;
        created: string;
    };
    user: {
        /**
         * Number of consecutive days of recording
         */
        repeat_count: number;
        /**
         * Total number of days with records
         */
        day_count: number;
        /**
         * Total number of inputs by the user
         */
        input_count: number;
    };
};

export type Other_Currency = {
    /**
     * Currency code
     */
    currency_code: string;
    /**
     * Currency unit symbol
     */
    unit: string;
    /**
     * Currency name
     */
    name: string;
    /**
     * Number of decimal points
     */
    point: number;
};

export type Other_DefaultAccount = {
    /**
     * Unique account ID
     */
    id: number;
    /**
     * Account name
     */
    name: string;
};

export type Other_DefaultCategory = {
    /**
     * Unique category ID
     */
    id: number;
    /**
     * Type of category: "payment" or "income"
     */
    mode: 'payment' | 'income';
    /**
     * Category name
     */
    name: string;
};

export type Other_DefaultGenre = {
    /**
     * Unique genre ID
     */
    id: number;
    /**
     * Category ID this genre belongs to
     */
    category_id: number;
    /**
     * Genre name
     */
    name: string;
};

export type User_User = {
    /**
     * Unique user ID
     */
    id: number;
    /**
     * Unique string for user login
     */
    login: string;
    /**
     * User name
     */
    name: string;
    /**
     * Total number of inputs
     */
    input_count: number;
    /**
     * Total number of days
     */
    day_count: number;
    /**
     * Days of continuous recording
     */
    repeat_count: number;
    /**
     * Start date of the month
     */
    day: number;
    /**
     * First day of the week
     */
    week: number;
    /**
     * Start date of the year
     */
    month: number;
    /**
     * Default currency code
     */
    currency_code: string;
    /**
     * URL of the user's profile image
     */
    profile_image_url: string;
    /**
     * URL of the user's cover image
     */
    cover_image_url: string;
    /**
     * Last modified time of the user's profile
     */
    profile_modified: string;
    /**
     * (Undocumented) Createed time of user
     */
    created: string;
};

/**
 * Amount without decimal point
 */
export type ParameterMoney_IncomeData_amount = number;

/**
 * Category ID for income
 */
export type ParameterMoney_IncomeData_category_id = number;

/**
 * Comment (within 100 characters)
 */
export type ParameterMoney_IncomeData_comment = string;

/**
 * Date in Y-m-d format (past three months)
 */
export type ParameterMoney_IncomeData_date = string;

/**
 * Required. Set to 1
 */
export type ParameterMoney_IncomeData_mapping = 1;

/**
 * Place name (within 100 characters)
 */
export type ParameterMoney_IncomeData_place = string;

/**
 * Account ID for income
 */
export type ParameterMoney_IncomeData_to_account_id = number;

/**
 * Amount without decimal point
 */
export type ParameterMoney_PaymentData_amount = number;

/**
 * Category ID for payment
 */
export type ParameterMoney_PaymentData_category_id = number;

/**
 * Comment (within 100 characters)
 */
export type ParameterMoney_PaymentData_comment = string;

/**
 * Date in Y-m-d format (past/future 5 years is valid)
 */
export type ParameterMoney_PaymentData_date = string;

/**
 * Account ID for payment
 */
export type ParameterMoney_PaymentData_from_account_id = number;

/**
 * Genre ID for payment
 */
export type ParameterMoney_PaymentData_genre_id = number;

/**
 * Required. Set to 1
 */
export type ParameterMoney_PaymentData_mapping = 1;

/**
 * Product name (within 100 characters)
 */
export type ParameterMoney_PaymentData_name = string;

/**
 * Place name (within 100 characters)
 */
export type ParameterMoney_PaymentData_place = string;

/**
 * (Undocumented) Place ID for payment
 */
export type ParameterMoney_PaymentData_place_uid = string;

/**
 * (Undocumented) Receipt ID for payment
 */
export type ParameterMoney_PaymentData_receipt_id = number;

/**
 * Amount without decimal point
 */
export type ParameterMoney_TransferData_amount = number;

/**
 * Comment (within 100 characters)
 */
export type ParameterMoney_TransferData_comment = string;

/**
 * Date in Y-m-d format (past/future 5 years is valid)
 */
export type ParameterMoney_TransferData_date = string;

/**
 * Account ID for transfer from
 */
export type ParameterMoney_TransferData_from_account_id = number;

/**
 * Required. Set to 1
 */
export type ParameterMoney_TransferData_mapping = 1;

/**
 * Account ID for transfer to
 */
export type ParameterMoney_TransferData_to_account_id = number;

export type OtherGetDefaultAccountsResponse = ({
    /**
     * List of default accounts
     */
    accounts: Array<Other_DefaultAccount>;
    requested: number;
});

export type OtherGetDefaultAccountsError = (ErrorResponse);

export type OtherGetDefaultCategoriesResponse = ({
    /**
     * List of default categories
     */
    categories: Array<Other_DefaultCategory>;
    requested: number;
});

export type OtherGetDefaultCategoriesError = (ErrorResponse);

export type OtherGetCurrenciesResponse = ({
    /**
     * List of currencies
     */
    currencies: Array<Other_Currency>;
    requested: number;
});

export type OtherGetCurrenciesError = (ErrorResponse);

export type OtherGetDefaultGenresResponse = ({
    /**
     * List of default genres
     */
    genres: Array<Other_DefaultGenre>;
    requested: number;
});

export type OtherGetDefaultGenresError = (ErrorResponse);

export type AccountGetAccountsData = {
    query: {
        /**
         * Required. Set to 1
         */
        mapping: 1;
    };
};

export type AccountGetAccountsResponse = ({
    /**
     * List of accounts
     */
    accounts: Array<Account_Account>;
    requested: number;
});

export type AccountGetAccountsError = (ErrorResponse);

export type CategoryGetCategoriesData = {
    query: {
        /**
         * Required. Set to 1
         */
        mapping: 1;
    };
};

export type CategoryGetCategoriesResponse = ({
    /**
     * List of categories
     */
    categories: Array<Category_Category>;
    requested: number;
});

export type CategoryGetCategoriesError = (ErrorResponse);

export type GenreGetGenresData = {
    query: {
        /**
         * Required. Set to 1
         */
        mapping: 1;
    };
};

export type GenreGetGenresResponse = ({
    /**
     * List of genres
     */
    genres: Array<Genre_Genre>;
    requested: number;
});

export type GenreGetGenresError = (ErrorResponse);

export type MoneyGetMoneyData = {
    query: {
        /**
         * Filter by category ID
         */
        category_id?: number;
        /**
         * End date in Y-m-d format
         */
        end_date?: string;
        /**
         * Filter by genre ID
         */
        genre_id?: number;
        /**
         * Group results by receipt_id
         */
        group_by?: 'receipt_id';
        /**
         * Number of items per page (default: 20, max: 100)
         */
        limit?: number;
        /**
         * Required. Set to 1
         */
        mapping: 1;
        /**
         * Filter by transaction type
         */
        mode?: 'payment' | 'income' | 'transfer';
        /**
         * Sort by id or date (default: date)
         */
        order?: 'id' | 'date';
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Start date in Y-m-d format
         */
        start_date?: string;
    };
};

export type MoneyGetMoneyResponse = ({
    /**
     * List of money transactions
     */
    money: Array<Money_Money>;
    requested: number;
});

export type MoneyGetMoneyError = (ErrorResponse);

export type IncomeOperationsCreateData = {
    query: {
        /**
         * Amount without decimal point
         */
        amount: number;
        /**
         * Category ID for income
         */
        category_id: number;
        /**
         * Comment (within 100 characters)
         */
        comment?: string;
        /**
         * Date in Y-m-d format (past three months)
         */
        date: string;
        /**
         * Required. Set to 1
         */
        mapping: 1;
        /**
         * Place name (within 100 characters)
         */
        place?: string;
        /**
         * Account ID for income
         */
        to_account_id?: number;
    };
};

export type IncomeOperationsCreateResponse = ({
    money: {
        /**
         * Unique ID given by Zaim for each input
         */
        id: number;
        /**
         * Modification timestamp
         */
        modified: string;
        /**
         * Place UID (only present if a place was specified)
         */
        place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
        id: number;
        user_id: number;
        genre_id: number;
        category_id: number;
        account_id: number;
        transfer_account_id: number;
        mode: string;
        place_uid: string;
        service: string;
        name: string;
        original_name: string;
        tel: string;
        count: number;
        place_pattern_id: number;
        calc_flag: number;
        edit_flag: number;
        active: number;
        modified: string;
        created: string;
    };
    user: {
        /**
         * Number of consecutive days of recording
         */
        repeat_count: number;
        /**
         * Total number of days with records
         */
        day_count: number;
        /**
         * Total number of inputs by the user
         */
        input_count: number;
    };
    requested: number;
});

export type IncomeOperationsCreateError = (ErrorResponse);

export type IncomeOperationsUpdateData = {
    path: {
        id: number;
    };
    query: {
        /**
         * Amount without decimal point
         */
        amount: number;
        /**
         * Category ID for income
         */
        category_id: number;
        /**
         * Comment (within 100 characters)
         */
        comment?: string;
        /**
         * Date in Y-m-d format (past three months)
         */
        date: string;
        /**
         * Required. Set to 1
         */
        mapping: 1;
        /**
         * Place name (within 100 characters)
         */
        place?: string;
        /**
         * Account ID for income
         */
        to_account_id?: number;
    };
};

export type IncomeOperationsUpdateResponse = ({
    money: {
        /**
         * Unique ID given by Zaim for each input
         */
        id: number;
        /**
         * Modification timestamp
         */
        modified: string;
        /**
         * Place UID (only present if a place was specified)
         */
        place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
        id: number;
        user_id: number;
        genre_id: number;
        category_id: number;
        account_id: number;
        transfer_account_id: number;
        mode: string;
        place_uid: string;
        service: string;
        name: string;
        original_name: string;
        tel: string;
        count: number;
        place_pattern_id: number;
        calc_flag: number;
        edit_flag: number;
        active: number;
        modified: string;
        created: string;
    };
    user: {
        /**
         * Number of consecutive days of recording
         */
        repeat_count: number;
        /**
         * Total number of days with records
         */
        day_count: number;
        /**
         * Total number of inputs by the user
         */
        input_count: number;
    };
    requested: number;
});

export type IncomeOperationsUpdateError = (ErrorResponse);

export type IncomeOperationsDeleteData = {
    path: {
        id: number;
    };
};

export type IncomeOperationsDeleteResponse = ({
    money: {
        /**
         * Unique ID given by Zaim for each input
         */
        id: number;
        /**
         * Modification timestamp
         */
        modified: string;
        /**
         * Place UID (only present if a place was specified)
         */
        place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
        id: number;
        user_id: number;
        genre_id: number;
        category_id: number;
        account_id: number;
        transfer_account_id: number;
        mode: string;
        place_uid: string;
        service: string;
        name: string;
        original_name: string;
        tel: string;
        count: number;
        place_pattern_id: number;
        calc_flag: number;
        edit_flag: number;
        active: number;
        modified: string;
        created: string;
    };
    user: {
        /**
         * Number of consecutive days of recording
         */
        repeat_count: number;
        /**
         * Total number of days with records
         */
        day_count: number;
        /**
         * Total number of inputs by the user
         */
        input_count: number;
    };
    requested: number;
});

export type IncomeOperationsDeleteError = (ErrorResponse);

export type PaymentOperationsCreateData = {
    query: {
        /**
         * Amount without decimal point
         */
        amount: number;
        /**
         * Category ID for payment
         */
        category_id: number;
        /**
         * Comment (within 100 characters)
         */
        comment?: string;
        /**
         * Date in Y-m-d format (past/future 5 years is valid)
         */
        date: string;
        /**
         * Account ID for payment
         */
        from_account_id?: number;
        /**
         * Genre ID for payment
         */
        genre_id: number;
        /**
         * Required. Set to 1
         */
        mapping: 1;
        /**
         * Product name (within 100 characters)
         */
        name?: string;
        /**
         * Place name (within 100 characters)
         */
        place?: string;
        /**
         * (Undocumented) Place ID for payment
         */
        place_uid?: string;
        /**
         * (Undocumented) Receipt ID for payment
         */
        receipt_id?: number;
    };
};

export type PaymentOperationsCreateResponse = ({
    money: {
        /**
         * Unique ID given by Zaim for each input
         */
        id: number;
        /**
         * Modification timestamp
         */
        modified: string;
        /**
         * Place UID (only present if a place was specified)
         */
        place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
        id: number;
        user_id: number;
        genre_id: number;
        category_id: number;
        account_id: number;
        transfer_account_id: number;
        mode: string;
        place_uid: string;
        service: string;
        name: string;
        original_name: string;
        tel: string;
        count: number;
        place_pattern_id: number;
        calc_flag: number;
        edit_flag: number;
        active: number;
        modified: string;
        created: string;
    };
    user: {
        /**
         * Number of consecutive days of recording
         */
        repeat_count: number;
        /**
         * Total number of days with records
         */
        day_count: number;
        /**
         * Total number of inputs by the user
         */
        input_count: number;
    };
    requested: number;
});

export type PaymentOperationsCreateError = (ErrorResponse);

export type PaymentOperationsUpdateData = {
    path: {
        id: number;
    };
    query: {
        /**
         * Amount without decimal point
         */
        amount: number;
        /**
         * Category ID for payment
         */
        category_id: number;
        /**
         * Comment (within 100 characters)
         */
        comment?: string;
        /**
         * Date in Y-m-d format (past/future 5 years is valid)
         */
        date: string;
        /**
         * Account ID for payment
         */
        from_account_id?: number;
        /**
         * Genre ID for payment
         */
        genre_id: number;
        /**
         * Required. Set to 1
         */
        mapping: 1;
        /**
         * Product name (within 100 characters)
         */
        name?: string;
        /**
         * Place name (within 100 characters)
         */
        place?: string;
        /**
         * (Undocumented) Place ID for payment
         */
        place_uid?: string;
        /**
         * (Undocumented) Receipt ID for payment
         */
        receipt_id?: number;
    };
};

export type PaymentOperationsUpdateResponse = ({
    money: {
        /**
         * Unique ID given by Zaim for each input
         */
        id: number;
        /**
         * Modification timestamp
         */
        modified: string;
        /**
         * Place UID (only present if a place was specified)
         */
        place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
        id: number;
        user_id: number;
        genre_id: number;
        category_id: number;
        account_id: number;
        transfer_account_id: number;
        mode: string;
        place_uid: string;
        service: string;
        name: string;
        original_name: string;
        tel: string;
        count: number;
        place_pattern_id: number;
        calc_flag: number;
        edit_flag: number;
        active: number;
        modified: string;
        created: string;
    };
    user: {
        /**
         * Number of consecutive days of recording
         */
        repeat_count: number;
        /**
         * Total number of days with records
         */
        day_count: number;
        /**
         * Total number of inputs by the user
         */
        input_count: number;
    };
    requested: number;
});

export type PaymentOperationsUpdateError = (ErrorResponse);

export type PaymentOperationsDeleteData = {
    path: {
        id: number;
    };
};

export type PaymentOperationsDeleteResponse = ({
    money: {
        /**
         * Unique ID given by Zaim for each input
         */
        id: number;
        /**
         * Modification timestamp
         */
        modified: string;
        /**
         * Place UID (only present if a place was specified)
         */
        place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
        id: number;
        user_id: number;
        genre_id: number;
        category_id: number;
        account_id: number;
        transfer_account_id: number;
        mode: string;
        place_uid: string;
        service: string;
        name: string;
        original_name: string;
        tel: string;
        count: number;
        place_pattern_id: number;
        calc_flag: number;
        edit_flag: number;
        active: number;
        modified: string;
        created: string;
    };
    user: {
        /**
         * Number of consecutive days of recording
         */
        repeat_count: number;
        /**
         * Total number of days with records
         */
        day_count: number;
        /**
         * Total number of inputs by the user
         */
        input_count: number;
    };
    requested: number;
});

export type PaymentOperationsDeleteError = (ErrorResponse);

export type TransferOperationsCreateData = {
    query: {
        /**
         * Amount without decimal point
         */
        amount: number;
        /**
         * Comment (within 100 characters)
         */
        comment?: string;
        /**
         * Date in Y-m-d format (past/future 5 years is valid)
         */
        date: string;
        /**
         * Account ID for transfer from
         */
        from_account_id: number;
        /**
         * Required. Set to 1
         */
        mapping: 1;
        /**
         * Account ID for transfer to
         */
        to_account_id: number;
    };
};

export type TransferOperationsCreateResponse = ({
    money: {
        /**
         * Unique ID given by Zaim for each input
         */
        id: number;
        /**
         * Modification timestamp
         */
        modified: string;
        /**
         * Place UID (only present if a place was specified)
         */
        place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
        id: number;
        user_id: number;
        genre_id: number;
        category_id: number;
        account_id: number;
        transfer_account_id: number;
        mode: string;
        place_uid: string;
        service: string;
        name: string;
        original_name: string;
        tel: string;
        count: number;
        place_pattern_id: number;
        calc_flag: number;
        edit_flag: number;
        active: number;
        modified: string;
        created: string;
    };
    user: {
        /**
         * Number of consecutive days of recording
         */
        repeat_count: number;
        /**
         * Total number of days with records
         */
        day_count: number;
        /**
         * Total number of inputs by the user
         */
        input_count: number;
    };
    requested: number;
});

export type TransferOperationsCreateError = (ErrorResponse);

export type TransferOperationsUpdateData = {
    path: {
        id: number;
    };
    query: {
        /**
         * Amount without decimal point
         */
        amount: number;
        /**
         * Comment (within 100 characters)
         */
        comment?: string;
        /**
         * Date in Y-m-d format (past/future 5 years is valid)
         */
        date: string;
        /**
         * Account ID for transfer from
         */
        from_account_id: number;
        /**
         * Required. Set to 1
         */
        mapping: 1;
        /**
         * Account ID for transfer to
         */
        to_account_id: number;
    };
};

export type TransferOperationsUpdateResponse = ({
    money: {
        /**
         * Unique ID given by Zaim for each input
         */
        id: number;
        /**
         * Modification timestamp
         */
        modified: string;
        /**
         * Place UID (only present if a place was specified)
         */
        place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
        id: number;
        user_id: number;
        genre_id: number;
        category_id: number;
        account_id: number;
        transfer_account_id: number;
        mode: string;
        place_uid: string;
        service: string;
        name: string;
        original_name: string;
        tel: string;
        count: number;
        place_pattern_id: number;
        calc_flag: number;
        edit_flag: number;
        active: number;
        modified: string;
        created: string;
    };
    user: {
        /**
         * Number of consecutive days of recording
         */
        repeat_count: number;
        /**
         * Total number of days with records
         */
        day_count: number;
        /**
         * Total number of inputs by the user
         */
        input_count: number;
    };
    requested: number;
});

export type TransferOperationsUpdateError = (ErrorResponse);

export type TransferOperationsDeleteData = {
    path: {
        id: number;
    };
};

export type TransferOperationsDeleteResponse = ({
    money: {
        /**
         * Unique ID given by Zaim for each input
         */
        id: number;
        /**
         * Modification timestamp
         */
        modified: string;
        /**
         * Place UID (only present if a place was specified)
         */
        place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
        id: number;
        user_id: number;
        genre_id: number;
        category_id: number;
        account_id: number;
        transfer_account_id: number;
        mode: string;
        place_uid: string;
        service: string;
        name: string;
        original_name: string;
        tel: string;
        count: number;
        place_pattern_id: number;
        calc_flag: number;
        edit_flag: number;
        active: number;
        modified: string;
        created: string;
    };
    user: {
        /**
         * Number of consecutive days of recording
         */
        repeat_count: number;
        /**
         * Total number of days with records
         */
        day_count: number;
        /**
         * Total number of inputs by the user
         */
        input_count: number;
    };
    requested: number;
});

export type TransferOperationsDeleteError = (ErrorResponse);

export type UserVerifyUserResponse = ({
    /**
     * User information
     */
    me: (User_User);
    requested: number;
});

export type UserVerifyUserError = (ErrorResponse);