// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type AccountAccount = {
  /**
   * Unique account ID
   */
  id: number;
  /**
   * Account name
   */
  name: string;
  /**
   * Last modified timestamp
   */
  modified: string;
  /**
   * Sort order
   */
  sort: number;
  /**
   * Active status
   */
  active: number;
  /**
   * Local account ID
   */
  local_id: number;
  /**
   * Website ID
   */
  website_id: number;
  /**
   * Parent account ID
   */
  parent_account_id: number;
};

export type CategoryCategory = {
  /**
   * Unique category ID
   */
  id: number;
  /**
   * Category name
   */
  name: string;
  /**
   * Type of category: "payment" or "income"
   */
  mode: "payment" | "income";
  /**
   * Sort order
   */
  sort: number;
  /**
   * Parent category ID
   */
  parent_category_id: number;
  /**
   * Active status
   */
  active: number;
  /**
   * Last modified timestamp
   */
  modified: string;
  /**
   * (Undocumented)
   */
  local_id: number;
};

export type ErrorResponse = {
  error: true;
  message: string;
};

export type GenreGenre = {
  /**
   * Unique genre ID
   */
  id: number;
  /**
   * Genre name
   */
  name: string;
  /**
   * Sort order
   */
  sort: number;
  /**
   * Active status
   */
  active: number;
  /**
   * Category ID this genre belongs to
   */
  category_id: number;
  /**
   * Parent genre ID
   */
  parent_genre_id: number;
  /**
   * Last modified timestamp
   */
  modified: string;
  /**
   * (Undocumented)
   */
  local_id: number;
};

export type MoneyMoney = {
  /**
   * Unique input id
   */
  id: number;
  /**
   * Type of transaction: income, payment, or transfer
   */
  mode: "income" | "payment" | "transfer";
  /**
   * User ID
   */
  user_id: number;
  /**
   * Date of the transaction in YYYY-MM-DD format
   */
  date: string;
  /**
   * Category ID
   */
  category_id: number;
  /**
   * Genre ID
   */
  genre_id: number;
  /**
   * Account ID for incoming transfer (for income or transfer)
   */
  to_account_id: number;
  /**
   * Account ID for outgoing transfer (for payment or transfer)
   */
  from_account_id: number;
  /**
   * Amount without decimal point
   */
  amount: number;
  /**
   * Comment or memo
   */
  comment: string;
  /**
   * Active status
   */
  active: number;
  /**
   * Name of the item or product
   */
  name: string;
  /**
   * Receipt ID
   */
  receipt_id: number;
  /**
   * Place name
   */
  place: string;
  /**
   * (Undocumented) Place unique ID
   */
  place_uid: string;
  /**
   * Creation timestamp
   */
  created: string;
  /**
   * Currency code
   */
  currency_code: string;
};

export type MoneyMoneyResponse = {
  money: {
    /**
     * Unique ID given by Zaim for each input
     */
    id: number;
    /**
     * Modification timestamp
     */
    modified: string;
    /**
     * Place UID (only present if a place was specified)
     */
    place_uid?: string;
  };
  /**
   * Place information (only present if a place was specified)
   */
  place?: {
    id: number;
    user_id: number;
    genre_id: number;
    category_id: number;
    account_id: number;
    transfer_account_id: number;
    mode: string;
    place_uid: string;
    service: string;
    name: string;
    original_name: string;
    tel: string;
    count: number;
    place_pattern_id: number;
    calc_flag: number;
    edit_flag: number;
    active: number;
    modified: string;
    created: string;
  };
  user: {
    /**
     * Number of consecutive days of recording
     */
    repeat_count: number;
    /**
     * Total number of days with records
     */
    day_count: number;
    /**
     * Total number of inputs by the user
     */
    input_count: number;
  };
};

export type OtherCurrency = {
  /**
   * Currency code
   */
  currency_code: string;
  /**
   * Currency unit symbol
   */
  unit: string;
  /**
   * Currency name
   */
  name: string;
  /**
   * Number of decimal points
   */
  point: number;
};

export type OtherDefaultAccount = {
  /**
   * Unique account ID
   */
  id: number;
  /**
   * Account name
   */
  name: string;
};

export type OtherDefaultCategory = {
  /**
   * Unique category ID
   */
  id: number;
  /**
   * Type of category: "payment" or "income"
   */
  mode: "payment" | "income";
  /**
   * Category name
   */
  name: string;
};

export type OtherDefaultGenre = {
  /**
   * Unique genre ID
   */
  id: number;
  /**
   * Category ID this genre belongs to
   */
  category_id: number;
  /**
   * Genre name
   */
  name: string;
};

export type UserUser = {
  /**
   * Unique user ID
   */
  id: number;
  /**
   * Unique string for user login
   */
  login: string;
  /**
   * User name
   */
  name: string;
  /**
   * Total number of inputs
   */
  input_count: number;
  /**
   * Total number of days
   */
  day_count: number;
  /**
   * Days of continuous recording
   */
  repeat_count: number;
  /**
   * Start date of the month
   */
  day: number;
  /**
   * First day of the week
   */
  week: number;
  /**
   * Start date of the year
   */
  month: number;
  /**
   * Default currency code
   */
  currency_code: string;
  /**
   * URL of the user's profile image
   */
  profile_image_url: string;
  /**
   * URL of the user's cover image
   */
  cover_image_url: string;
  /**
   * Last modified time of the user's profile
   */
  profile_modified: string;
  /**
   * (Undocumented) Createed time of user
   */
  created: string;
};

/**
 * Amount without decimal point
 */
export type MoneyIncomeDataAmount = number;

/**
 * Category ID for income
 */
export type MoneyIncomeDataCategoryId = number;

/**
 * Comment (within 100 characters)
 */
export type MoneyIncomeDataComment = string;

/**
 * Date in Y-m-d format (past three months)
 */
export type MoneyIncomeDataDate = string;

/**
 * Required. Set to 1
 */
export type MoneyIncomeDataMapping = 1;

/**
 * Place name (within 100 characters)
 */
export type MoneyIncomeDataPlace = string;

/**
 * Account ID for income
 */
export type MoneyIncomeDataToAccountId = number;

/**
 * Amount without decimal point
 */
export type MoneyPaymentDataAmount = number;

/**
 * Category ID for payment
 */
export type MoneyPaymentDataCategoryId = number;

/**
 * Comment (within 100 characters)
 */
export type MoneyPaymentDataComment = string;

/**
 * Date in Y-m-d format (past/future 5 years is valid)
 */
export type MoneyPaymentDataDate = string;

/**
 * Account ID for payment
 */
export type MoneyPaymentDataFromAccountId = number;

/**
 * Genre ID for payment
 */
export type MoneyPaymentDataGenreId = number;

/**
 * Required. Set to 1
 */
export type MoneyPaymentDataMapping = 1;

/**
 * Product name (within 100 characters)
 */
export type MoneyPaymentDataName = string;

/**
 * Place name (within 100 characters)
 */
export type MoneyPaymentDataPlace = string;

/**
 * (Undocumented) Place ID for payment
 */
export type MoneyPaymentDataPlaceUid = string;

/**
 * (Undocumented) Receipt ID for payment
 */
export type MoneyPaymentDataReceiptId = number;

/**
 * Amount without decimal point
 */
export type MoneyTransferDataAmount = number;

/**
 * Comment (within 100 characters)
 */
export type MoneyTransferDataComment = string;

/**
 * Date in Y-m-d format (past/future 5 years is valid)
 */
export type MoneyTransferDataDate = string;

/**
 * Account ID for transfer from
 */
export type MoneyTransferDataFromAccountId = number;

/**
 * Required. Set to 1
 */
export type MoneyTransferDataMapping = 1;

/**
 * Account ID for transfer to
 */
export type MoneyTransferDataToAccountId = number;

export type OtherGetDefaultAccountsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/account";
};

export type OtherGetDefaultAccountsErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type OtherGetDefaultAccountsError =
  OtherGetDefaultAccountsErrors[keyof OtherGetDefaultAccountsErrors];

export type OtherGetDefaultAccountsResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    /**
     * List of default accounts
     */
    accounts: Array<OtherDefaultAccount>;
    requested: number;
  };
};

export type OtherGetDefaultAccountsResponse =
  OtherGetDefaultAccountsResponses[keyof OtherGetDefaultAccountsResponses];

export type OtherGetDefaultCategoriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/category";
};

export type OtherGetDefaultCategoriesErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type OtherGetDefaultCategoriesError =
  OtherGetDefaultCategoriesErrors[keyof OtherGetDefaultCategoriesErrors];

export type OtherGetDefaultCategoriesResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    /**
     * List of default categories
     */
    categories: Array<OtherDefaultCategory>;
    requested: number;
  };
};

export type OtherGetDefaultCategoriesResponse =
  OtherGetDefaultCategoriesResponses[keyof OtherGetDefaultCategoriesResponses];

export type OtherGetCurrenciesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/currency";
};

export type OtherGetCurrenciesErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type OtherGetCurrenciesError = OtherGetCurrenciesErrors[keyof OtherGetCurrenciesErrors];

export type OtherGetCurrenciesResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    /**
     * List of currencies
     */
    currencies: Array<OtherCurrency>;
    requested: number;
  };
};

export type OtherGetCurrenciesResponse =
  OtherGetCurrenciesResponses[keyof OtherGetCurrenciesResponses];

export type OtherGetDefaultGenresData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/genre";
};

export type OtherGetDefaultGenresErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type OtherGetDefaultGenresError =
  OtherGetDefaultGenresErrors[keyof OtherGetDefaultGenresErrors];

export type OtherGetDefaultGenresResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    /**
     * List of default genres
     */
    genres: Array<OtherDefaultGenre>;
    requested: number;
  };
};

export type OtherGetDefaultGenresResponse =
  OtherGetDefaultGenresResponses[keyof OtherGetDefaultGenresResponses];

export type AccountGetAccountsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Required. Set to 1
     */
    mapping: 1;
  };
  url: "/v2/home/account";
};

export type AccountGetAccountsErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type AccountGetAccountsError = AccountGetAccountsErrors[keyof AccountGetAccountsErrors];

export type AccountGetAccountsResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    /**
     * List of accounts
     */
    accounts: Array<AccountAccount>;
    requested: number;
  };
};

export type AccountGetAccountsResponse =
  AccountGetAccountsResponses[keyof AccountGetAccountsResponses];

export type CategoryGetCategoriesData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Required. Set to 1
     */
    mapping: 1;
  };
  url: "/v2/home/category";
};

export type CategoryGetCategoriesErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type CategoryGetCategoriesError =
  CategoryGetCategoriesErrors[keyof CategoryGetCategoriesErrors];

export type CategoryGetCategoriesResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    /**
     * List of categories
     */
    categories: Array<CategoryCategory>;
    requested: number;
  };
};

export type CategoryGetCategoriesResponse =
  CategoryGetCategoriesResponses[keyof CategoryGetCategoriesResponses];

export type GenreGetGenresData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Required. Set to 1
     */
    mapping: 1;
  };
  url: "/v2/home/genre";
};

export type GenreGetGenresErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type GenreGetGenresError = GenreGetGenresErrors[keyof GenreGetGenresErrors];

export type GenreGetGenresResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    /**
     * List of genres
     */
    genres: Array<GenreGenre>;
    requested: number;
  };
};

export type GenreGetGenresResponse = GenreGetGenresResponses[keyof GenreGetGenresResponses];

export type MoneyGetMoneyData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Required. Set to 1
     */
    mapping: 1;
    /**
     * Filter by category ID
     */
    category_id?: number;
    /**
     * Filter by genre ID
     */
    genre_id?: number;
    /**
     * Filter by transaction type
     */
    mode?: "payment" | "income" | "transfer";
    /**
     * Sort by id or date (default: date)
     */
    order?: "id" | "date";
    /**
     * Start date in Y-m-d format
     */
    start_date?: string;
    /**
     * End date in Y-m-d format
     */
    end_date?: string;
    /**
     * Page number (default: 1)
     */
    page?: number;
    /**
     * Number of items per page (default: 20, max: 100)
     */
    limit?: number;
    /**
     * Group results by receipt_id
     */
    group_by?: "receipt_id";
  };
  url: "/v2/home/money";
};

export type MoneyGetMoneyErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type MoneyGetMoneyError = MoneyGetMoneyErrors[keyof MoneyGetMoneyErrors];

export type MoneyGetMoneyResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    /**
     * List of money transactions
     */
    money: Array<MoneyMoney>;
    requested: number;
  };
};

export type MoneyGetMoneyResponse = MoneyGetMoneyResponses[keyof MoneyGetMoneyResponses];

export type IncomeOperationsCreateData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Required. Set to 1
     */
    mapping: 1;
    /**
     * Category ID for income
     */
    category_id: number;
    /**
     * Amount without decimal point
     */
    amount: number;
    /**
     * Date in Y-m-d format (past three months)
     */
    date: string;
    /**
     * Account ID for income
     */
    to_account_id?: number;
    /**
     * Place name (within 100 characters)
     */
    place?: string;
    /**
     * Comment (within 100 characters)
     */
    comment?: string;
  };
  url: "/v2/home/money/income";
};

export type IncomeOperationsCreateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type IncomeOperationsCreateError =
  IncomeOperationsCreateErrors[keyof IncomeOperationsCreateErrors];

export type IncomeOperationsCreateResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    money: {
      /**
       * Unique ID given by Zaim for each input
       */
      id: number;
      /**
       * Modification timestamp
       */
      modified: string;
      /**
       * Place UID (only present if a place was specified)
       */
      place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
      id: number;
      user_id: number;
      genre_id: number;
      category_id: number;
      account_id: number;
      transfer_account_id: number;
      mode: string;
      place_uid: string;
      service: string;
      name: string;
      original_name: string;
      tel: string;
      count: number;
      place_pattern_id: number;
      calc_flag: number;
      edit_flag: number;
      active: number;
      modified: string;
      created: string;
    };
    user: {
      /**
       * Number of consecutive days of recording
       */
      repeat_count: number;
      /**
       * Total number of days with records
       */
      day_count: number;
      /**
       * Total number of inputs by the user
       */
      input_count: number;
    };
    requested: number;
  };
};

export type IncomeOperationsCreateResponse =
  IncomeOperationsCreateResponses[keyof IncomeOperationsCreateResponses];

export type IncomeOperationsDeleteData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/v2/home/money/income/{id}";
};

export type IncomeOperationsDeleteErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type IncomeOperationsDeleteError =
  IncomeOperationsDeleteErrors[keyof IncomeOperationsDeleteErrors];

export type IncomeOperationsDeleteResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    money: {
      /**
       * Unique ID given by Zaim for each input
       */
      id: number;
      /**
       * Modification timestamp
       */
      modified: string;
      /**
       * Place UID (only present if a place was specified)
       */
      place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
      id: number;
      user_id: number;
      genre_id: number;
      category_id: number;
      account_id: number;
      transfer_account_id: number;
      mode: string;
      place_uid: string;
      service: string;
      name: string;
      original_name: string;
      tel: string;
      count: number;
      place_pattern_id: number;
      calc_flag: number;
      edit_flag: number;
      active: number;
      modified: string;
      created: string;
    };
    user: {
      /**
       * Number of consecutive days of recording
       */
      repeat_count: number;
      /**
       * Total number of days with records
       */
      day_count: number;
      /**
       * Total number of inputs by the user
       */
      input_count: number;
    };
    requested: number;
  };
};

export type IncomeOperationsDeleteResponse =
  IncomeOperationsDeleteResponses[keyof IncomeOperationsDeleteResponses];

export type IncomeOperationsUpdateData = {
  body?: never;
  path: {
    id: number;
  };
  query: {
    /**
     * Required. Set to 1
     */
    mapping: 1;
    /**
     * Category ID for income
     */
    category_id: number;
    /**
     * Amount without decimal point
     */
    amount: number;
    /**
     * Date in Y-m-d format (past three months)
     */
    date: string;
    /**
     * Account ID for income
     */
    to_account_id?: number;
    /**
     * Place name (within 100 characters)
     */
    place?: string;
    /**
     * Comment (within 100 characters)
     */
    comment?: string;
  };
  url: "/v2/home/money/income/{id}";
};

export type IncomeOperationsUpdateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type IncomeOperationsUpdateError =
  IncomeOperationsUpdateErrors[keyof IncomeOperationsUpdateErrors];

export type IncomeOperationsUpdateResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    money: {
      /**
       * Unique ID given by Zaim for each input
       */
      id: number;
      /**
       * Modification timestamp
       */
      modified: string;
      /**
       * Place UID (only present if a place was specified)
       */
      place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
      id: number;
      user_id: number;
      genre_id: number;
      category_id: number;
      account_id: number;
      transfer_account_id: number;
      mode: string;
      place_uid: string;
      service: string;
      name: string;
      original_name: string;
      tel: string;
      count: number;
      place_pattern_id: number;
      calc_flag: number;
      edit_flag: number;
      active: number;
      modified: string;
      created: string;
    };
    user: {
      /**
       * Number of consecutive days of recording
       */
      repeat_count: number;
      /**
       * Total number of days with records
       */
      day_count: number;
      /**
       * Total number of inputs by the user
       */
      input_count: number;
    };
    requested: number;
  };
};

export type IncomeOperationsUpdateResponse =
  IncomeOperationsUpdateResponses[keyof IncomeOperationsUpdateResponses];

export type PaymentOperationsCreateData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Required. Set to 1
     */
    mapping: 1;
    /**
     * Category ID for payment
     */
    category_id: number;
    /**
     * Genre ID for payment
     */
    genre_id: number;
    /**
     * Amount without decimal point
     */
    amount: number;
    /**
     * Date in Y-m-d format (past/future 5 years is valid)
     */
    date: string;
    /**
     * Account ID for payment
     */
    from_account_id?: number;
    /**
     * Comment (within 100 characters)
     */
    comment?: string;
    /**
     * Product name (within 100 characters)
     */
    name?: string;
    /**
     * Place name (within 100 characters)
     */
    place?: string;
    /**
     * (Undocumented) Place ID for payment
     */
    place_uid?: string;
    /**
     * (Undocumented) Receipt ID for payment
     */
    receipt_id?: number;
  };
  url: "/v2/home/money/payment";
};

export type PaymentOperationsCreateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type PaymentOperationsCreateError =
  PaymentOperationsCreateErrors[keyof PaymentOperationsCreateErrors];

export type PaymentOperationsCreateResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    money: {
      /**
       * Unique ID given by Zaim for each input
       */
      id: number;
      /**
       * Modification timestamp
       */
      modified: string;
      /**
       * Place UID (only present if a place was specified)
       */
      place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
      id: number;
      user_id: number;
      genre_id: number;
      category_id: number;
      account_id: number;
      transfer_account_id: number;
      mode: string;
      place_uid: string;
      service: string;
      name: string;
      original_name: string;
      tel: string;
      count: number;
      place_pattern_id: number;
      calc_flag: number;
      edit_flag: number;
      active: number;
      modified: string;
      created: string;
    };
    user: {
      /**
       * Number of consecutive days of recording
       */
      repeat_count: number;
      /**
       * Total number of days with records
       */
      day_count: number;
      /**
       * Total number of inputs by the user
       */
      input_count: number;
    };
    requested: number;
  };
};

export type PaymentOperationsCreateResponse =
  PaymentOperationsCreateResponses[keyof PaymentOperationsCreateResponses];

export type PaymentOperationsDeleteData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/v2/home/money/payment/{id}";
};

export type PaymentOperationsDeleteErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type PaymentOperationsDeleteError =
  PaymentOperationsDeleteErrors[keyof PaymentOperationsDeleteErrors];

export type PaymentOperationsDeleteResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    money: {
      /**
       * Unique ID given by Zaim for each input
       */
      id: number;
      /**
       * Modification timestamp
       */
      modified: string;
      /**
       * Place UID (only present if a place was specified)
       */
      place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
      id: number;
      user_id: number;
      genre_id: number;
      category_id: number;
      account_id: number;
      transfer_account_id: number;
      mode: string;
      place_uid: string;
      service: string;
      name: string;
      original_name: string;
      tel: string;
      count: number;
      place_pattern_id: number;
      calc_flag: number;
      edit_flag: number;
      active: number;
      modified: string;
      created: string;
    };
    user: {
      /**
       * Number of consecutive days of recording
       */
      repeat_count: number;
      /**
       * Total number of days with records
       */
      day_count: number;
      /**
       * Total number of inputs by the user
       */
      input_count: number;
    };
    requested: number;
  };
};

export type PaymentOperationsDeleteResponse =
  PaymentOperationsDeleteResponses[keyof PaymentOperationsDeleteResponses];

export type PaymentOperationsUpdateData = {
  body?: never;
  path: {
    id: number;
  };
  query: {
    /**
     * Required. Set to 1
     */
    mapping: 1;
    /**
     * Category ID for payment
     */
    category_id: number;
    /**
     * Genre ID for payment
     */
    genre_id: number;
    /**
     * Amount without decimal point
     */
    amount: number;
    /**
     * Date in Y-m-d format (past/future 5 years is valid)
     */
    date: string;
    /**
     * Account ID for payment
     */
    from_account_id?: number;
    /**
     * Comment (within 100 characters)
     */
    comment?: string;
    /**
     * Product name (within 100 characters)
     */
    name?: string;
    /**
     * Place name (within 100 characters)
     */
    place?: string;
    /**
     * (Undocumented) Place ID for payment
     */
    place_uid?: string;
    /**
     * (Undocumented) Receipt ID for payment
     */
    receipt_id?: number;
  };
  url: "/v2/home/money/payment/{id}";
};

export type PaymentOperationsUpdateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type PaymentOperationsUpdateError =
  PaymentOperationsUpdateErrors[keyof PaymentOperationsUpdateErrors];

export type PaymentOperationsUpdateResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    money: {
      /**
       * Unique ID given by Zaim for each input
       */
      id: number;
      /**
       * Modification timestamp
       */
      modified: string;
      /**
       * Place UID (only present if a place was specified)
       */
      place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
      id: number;
      user_id: number;
      genre_id: number;
      category_id: number;
      account_id: number;
      transfer_account_id: number;
      mode: string;
      place_uid: string;
      service: string;
      name: string;
      original_name: string;
      tel: string;
      count: number;
      place_pattern_id: number;
      calc_flag: number;
      edit_flag: number;
      active: number;
      modified: string;
      created: string;
    };
    user: {
      /**
       * Number of consecutive days of recording
       */
      repeat_count: number;
      /**
       * Total number of days with records
       */
      day_count: number;
      /**
       * Total number of inputs by the user
       */
      input_count: number;
    };
    requested: number;
  };
};

export type PaymentOperationsUpdateResponse =
  PaymentOperationsUpdateResponses[keyof PaymentOperationsUpdateResponses];

export type TransferOperationsCreateData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Required. Set to 1
     */
    mapping: 1;
    /**
     * Amount without decimal point
     */
    amount: number;
    /**
     * Date in Y-m-d format (past/future 5 years is valid)
     */
    date: string;
    /**
     * Account ID for transfer from
     */
    from_account_id: number;
    /**
     * Account ID for transfer to
     */
    to_account_id: number;
    /**
     * Comment (within 100 characters)
     */
    comment?: string;
  };
  url: "/v2/home/money/transfer";
};

export type TransferOperationsCreateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type TransferOperationsCreateError =
  TransferOperationsCreateErrors[keyof TransferOperationsCreateErrors];

export type TransferOperationsCreateResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    money: {
      /**
       * Unique ID given by Zaim for each input
       */
      id: number;
      /**
       * Modification timestamp
       */
      modified: string;
      /**
       * Place UID (only present if a place was specified)
       */
      place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
      id: number;
      user_id: number;
      genre_id: number;
      category_id: number;
      account_id: number;
      transfer_account_id: number;
      mode: string;
      place_uid: string;
      service: string;
      name: string;
      original_name: string;
      tel: string;
      count: number;
      place_pattern_id: number;
      calc_flag: number;
      edit_flag: number;
      active: number;
      modified: string;
      created: string;
    };
    user: {
      /**
       * Number of consecutive days of recording
       */
      repeat_count: number;
      /**
       * Total number of days with records
       */
      day_count: number;
      /**
       * Total number of inputs by the user
       */
      input_count: number;
    };
    requested: number;
  };
};

export type TransferOperationsCreateResponse =
  TransferOperationsCreateResponses[keyof TransferOperationsCreateResponses];

export type TransferOperationsDeleteData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/v2/home/money/transfer/{id}";
};

export type TransferOperationsDeleteErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type TransferOperationsDeleteError =
  TransferOperationsDeleteErrors[keyof TransferOperationsDeleteErrors];

export type TransferOperationsDeleteResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    money: {
      /**
       * Unique ID given by Zaim for each input
       */
      id: number;
      /**
       * Modification timestamp
       */
      modified: string;
      /**
       * Place UID (only present if a place was specified)
       */
      place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
      id: number;
      user_id: number;
      genre_id: number;
      category_id: number;
      account_id: number;
      transfer_account_id: number;
      mode: string;
      place_uid: string;
      service: string;
      name: string;
      original_name: string;
      tel: string;
      count: number;
      place_pattern_id: number;
      calc_flag: number;
      edit_flag: number;
      active: number;
      modified: string;
      created: string;
    };
    user: {
      /**
       * Number of consecutive days of recording
       */
      repeat_count: number;
      /**
       * Total number of days with records
       */
      day_count: number;
      /**
       * Total number of inputs by the user
       */
      input_count: number;
    };
    requested: number;
  };
};

export type TransferOperationsDeleteResponse =
  TransferOperationsDeleteResponses[keyof TransferOperationsDeleteResponses];

export type TransferOperationsUpdateData = {
  body?: never;
  path: {
    id: number;
  };
  query: {
    /**
     * Required. Set to 1
     */
    mapping: 1;
    /**
     * Amount without decimal point
     */
    amount: number;
    /**
     * Date in Y-m-d format (past/future 5 years is valid)
     */
    date: string;
    /**
     * Account ID for transfer from
     */
    from_account_id: number;
    /**
     * Account ID for transfer to
     */
    to_account_id: number;
    /**
     * Comment (within 100 characters)
     */
    comment?: string;
  };
  url: "/v2/home/money/transfer/{id}";
};

export type TransferOperationsUpdateErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type TransferOperationsUpdateError =
  TransferOperationsUpdateErrors[keyof TransferOperationsUpdateErrors];

export type TransferOperationsUpdateResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    money: {
      /**
       * Unique ID given by Zaim for each input
       */
      id: number;
      /**
       * Modification timestamp
       */
      modified: string;
      /**
       * Place UID (only present if a place was specified)
       */
      place_uid?: string;
    };
    /**
     * Place information (only present if a place was specified)
     */
    place?: {
      id: number;
      user_id: number;
      genre_id: number;
      category_id: number;
      account_id: number;
      transfer_account_id: number;
      mode: string;
      place_uid: string;
      service: string;
      name: string;
      original_name: string;
      tel: string;
      count: number;
      place_pattern_id: number;
      calc_flag: number;
      edit_flag: number;
      active: number;
      modified: string;
      created: string;
    };
    user: {
      /**
       * Number of consecutive days of recording
       */
      repeat_count: number;
      /**
       * Total number of days with records
       */
      day_count: number;
      /**
       * Total number of inputs by the user
       */
      input_count: number;
    };
    requested: number;
  };
};

export type TransferOperationsUpdateResponse =
  TransferOperationsUpdateResponses[keyof TransferOperationsUpdateResponses];

export type UserVerifyUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/home/user/verify";
};

export type UserVerifyUserErrors = {
  /**
   * The server could not understand the request due to invalid syntax.
   */
  400: ErrorResponse;
  /**
   * Access is unauthorized.
   */
  401: ErrorResponse;
};

export type UserVerifyUserError = UserVerifyUserErrors[keyof UserVerifyUserErrors];

export type UserVerifyUserResponses = {
  /**
   * The request has succeeded.
   */
  200: {
    /**
     * User information
     */
    me: UserUser;
    requested: number;
  };
};

export type UserVerifyUserResponse = UserVerifyUserResponses[keyof UserVerifyUserResponses];
